### ISSUE TITLE
Issues when `.graphql` files are contained in directory with a "\s" character in their name.

### ISSUE THREAD

**Issue by justinmakaila** [apollographql/apollo-codegen#112]
My project has a directory structure like so:
```
My Project
  |- Screens
      |- Main
          |- Change Password
          |- Advanced Settings
          |- Camera
          |- ...
```

When running the `apollo-codegen generate $(find . -name '*.graphql') --schema path/to/schema.json --output path/to/output.swift`, I get an error (customized to reflect the example above):

```
Error: ENOENT: no such file or directory, open '/path/to/MyProject/MyProjectSource/Screens/Main/Change'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at inputPaths.map.inputPath (/usr/local/lib/node_modules/apollo-codegen/src/loading.js:28:21)
    at Array.map (native)
    at loadAndMergeQueryDocuments (/usr/local/lib/node_modules/apollo-codegen/src/loading.js:27:30)
    at generate (/usr/local/lib/node_modules/apollo-codegen/src/generate.js:15:20)
    at Object._yargs2.default.command.command.argv [as handler] (/usr/local/lib/node_modules/apollo-codegen/src/cli.js:110:9)
    at Object.self.runCommand (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/lib/command.js:170:22)
    at parseArgs (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:920:28)
    at Object.get [as argv] (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:860:16)
Command /bin/sh failed with exit code 1
```

It looks like the script isn't considering directories/folders with "\s" in their name.

Is there an easy fix?

**Comment by martijnwalraven** [comment]
You could try using the Node `glob` support instead of letting the shell expand the pattern.

Something like: `apollo-codegen generate '**/*.graphql' --schema path/to/schema.json --output path/to/output.swift`

**Comment by justinmakaila** [comment]
Thanks!
