### ISSUE TITLE
`fs.default` is undefined

### ISSUE THREAD

**Issue by blaugold** [apollographql/apollo-codegen#152]
Version: apollo-codegen@0.13.1

I installed the latest version and ran the following command:
```
node_modules/.bin/apollo-codegen introspect-schema src/schema.graphqls --output out/schema.json
```

This results in the following error:
```
TypeError: Cannot read property 'existsSync' of undefined
    at Object.<anonymous> (/Users/gabrielterwesten/Dev/apps/apollo-sandbox/node_modules/apollo-codegen/src/introspectSchema.js:14:10)
    at Generator.next (<anonymous>)
    at /Users/gabrielterwesten/Dev/apps/apollo-sandbox/node_modules/apollo-codegen/lib/introspectSchema.js:7:71
    at __awaiter (/Users/gabrielterwesten/Dev/apps/apollo-sandbox/node_modules/apollo-codegen/lib/introspectSchema.js:3:12)
    at Object.introspectSchema (/Users/gabrielterwesten/Dev/apps/apollo-sandbox/node_modules/apollo-codegen/lib/introspectSchema.js:23:12)
    at Object.<anonymous> (/Users/gabrielterwesten/Dev/apps/apollo-sandbox/node_modules/apollo-codegen/src/cli.js:64:15)
    at Generator.next (<anonymous>)
    at /Users/gabrielterwesten/Dev/apps/apollo-sandbox/node_modules/apollo-codegen/lib/cli.js:8:71
    at __awaiter (/Users/gabrielterwesten/Dev/apps/apollo-sandbox/node_modules/apollo-codegen/lib/cli.js:4:12)
    at Object.yargs.command [as handler] (/Users/gabrielterwesten/Dev/apps/apollo-sandbox/node_modules/apollo-codegen/src/cli.js:57:15)
```

The offending line is:
```
 if (!fs_1.default.existsSync(schemaPath)) {
```

As I understand the `fs` module has no export `default`.

I have submitted a [pr](https://github.com/apollographql/apollo-codegen/pull/153) to fix the import.

**Comment by lewisf** [comment]
Fix will come with the next release
