### ISSUE TITLE
Issues with ts-modern target

### ISSUE THREAD

**Issue by clayne11** [apollographql/apollo-codegen#352]
Trying to generate types using the `ts-modern` target I get the following error:

```
$ apollo-codegen generate packages/casalova-web-client/src/client/**/*.graphql --schema ./packages/casalova-web-client/src/universal/shared/graphql-schema.json --target ts-modern --output ./packages/casalova-web-client/src/universal/graphql-schema.d.ts --addTypename
TypeError: Property types[1] of UnionTypeAnnotation expected node to be of a type ["FlowType"] but instead got "TSUndefinedKeyword"
    at validate (/Users/clayne/workspace/casalova-web-two/node_modules/apollo-codegen/node_modules/@babel/types/lib/definitions/utils.js:136:13)
    at validator (/Users/clayne/workspace/casalova-web-two/node_modules/apollo-codegen/node_modules/@babel/types/lib/definitions/utils.js:95:7)
    at Object.validate (/Users/clayne/workspace/casalova-web-two/node_modules/apollo-codegen/node_modules/@babel/types/lib/definitions/utils.js:191:10)
    at validate (/Users/clayne/workspace/casalova-web-two/node_modules/apollo-codegen/node_modules/@babel/types/lib/validators/validate.js:15:9)
    at builder (/Users/clayne/workspace/casalova-web-two/node_modules/apollo-codegen/node_modules/@babel/types/lib/builders/builder.js:40:27)
    at Object.UnionTypeAnnotation (/Users/clayne/workspace/casalova-web-two/node_modules/apollo-codegen/node_modules/@babel/types/lib/builders/generated/index.js:1188:27)
    at TypescriptAPIGenerator.makeNullableAnnotation (/Users/clayne/workspace/casalova-web-two/node_modules/apollo-codegen/src/javascript/typescript/language.ts:169:14)
    at t.objectTypeAnnotation.fields.map (/Users/clayne/workspace/casalova-web-two/node_modules/apollo-codegen/src/javascript/typescript/language.ts:104:20)
    at Array.map (<anonymous>)
    at TypescriptAPIGenerator.objectTypeAnnotation (/Users/clayne/workspace/casalova-web-two/node_modules/apollo-codegen/src/javascript/typescript/language.ts:94:14)
```

**Comment by sgoll** [comment]
I think this is the commit that breaks `apollo-codegen`: babel/babel@4208099f5b3d95076ea58f029be155f26132d88b

For now, going back to package version `@babel/types@7.0.0-beta.36` helps.
