### ISSUE TITLE
Build fails on Windows 10 (java.io.IOException: Unable to delete file)

### ISSUE THREAD

**Issue by TealOcean** [apollographql/apollo-codegen#381]
Environment:
Gradle 4.5.1
Java 1.8
Windows 10 Pro
Apollo Gradle Plugin 0.4.4 (Using it's built-in code gen)

Problem:
I've noticed I'm able to build successfully using the plugin as long as the Gradle daemon remains active; however, if the daemon is ever torn down (Ex: Using ./gradlew --stop), I am unable to build successfully (./gradlew assembleDebug) until I clear out the build folder manually (not ideal).

I wind up with this error on my command line:

```
FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: Unable to delete file: E:\GitHub\coolapp\build\apollo-codegen\node_modules\apollo-codegen\package.json
> Unable to delete file: E:\GitHub\coolapp\build\apollo-codegen\node_modules\apollo-codegen\package.json

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.UncheckedIOException: java.io.IOException: Unable to delete file: E:\GitHub\eatable-taster\Eat\EatData\build\apollo-codegen\node_modules\apollo-codegen\package.json
        at org.gradle.util.GFileUtils.forceDelete(GFileUtils.java:213)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter$1.run(CleanupStaleOutputsExecuter.java:75)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:623)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:578)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.io.IOException: Unable to delete file: E:\GitHub\eatable-taster\Eat\EatData\build\apollo-codegen\node_modules\apollo-codegen\package.json
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2106)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1583)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1465)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2097)
        at org.gradle.util.GFileUtils.forceDelete(GFileUtils.java:211)
        ... 28 more


* Get more help at https://help.gradle.org
```

**Comment by martijnwalraven** [comment]
Please open an issue on the [Apollo Android repo](https://github.com/apollographql/apollo-android), because this seems related to the Gradle integration there and not the codegen tool itself.
