### ISSUE TITLE
codegen failed with exit code 1

### ISSUE THREAD

**Issue by omeryarn** [apollographql/apollo-codegen#400]
Using codegen as a build step in xcode generates this error:

Command /bin/sh failed with exit code 1
++ exec apollo-codegen generate --schema schema.json --output API.swift
TypeError: Cannot read property 'length' of undefined
at Object.yargs.command.command.command.argv [as handler] (/usr/local/lib/node_modules/apollo-codegen/src/cli.js:186:17)
at Object.runCommand (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/apollo-codegen/lib/cli.js:197:5)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

Not sure if this is a codegen issue or something very specific to my project (first time I'm trying this), so any help would be appreciated!

**Comment by martijnwalraven** [comment]
This should generate a better error message, but it means you're trying to invoke codegen without any `.graphql` files (which contain the queries).

**Comment by omeryarn** [comment]
That was it, thanks!
