### ISSUE TITLE
Error when running the codegen: Cannot redefine property: flatMap

### ISSUE THREAD

**Issue by Dremora** [apollographql/apollo-codegen#439]
I get the following error when running codegen after the upgrade:

```
node_modules/apollo-codegen-core/lib/utilities/array.js:3
Object.defineProperty(Array.prototype, 'flatMap', {
       ^

TypeError: Cannot redefine property: flatMap
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (node_modules/apollo-codegen-core/lib/utilities/array.js:3:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (node_modules/apollo-codegen-swift/lib/codeGeneration.js:13:1)
```

Library version: 0.20.0
Node: 8.10.0

**Comment by lsanwick** [comment]
I'm seeing this issue as well, reverting back to v0.19.x fixes the problem.

**Comment by mwarger** [comment]
I'm still seeing this issue, but I only see it when running it using an npm script within my project with `npm run generate-graphql-schema` like below.

```
"generate-graphql-schema": "apollo-codegen introspect-schema ./schema.graphql --output schema.json",
```

I can run the command using the globally installed version and it works fine.

Stacktrace:
```
node_modules\apollo-codegen-core\lib\utilities\array.js:3
Object.defineProperty(Array.prototype, 'flatMap', {
       ^

TypeError: Cannot redefine property: flatMap
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (node_modules\apollo-codegen-core\lib\utilities\array.js:3:8)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (node_modules\apollo-codegen-swift\lib\codeGeneration.js:13:1)
```

If this should be a new issue, please let me know.  Thanks for any insight.

Library: 0.20.2
Node: v10.5.0

**Comment by shadaj** [comment]
@mwarger can you try updating your dependencies? `apollo-codegen-core@0.20.1` was just published with a fix.

**Comment by mwarger** [comment]
I have updated to the latest on all dependencies, as far as I can tell.  I don't actually have `apollo-codegen-core` as a `devDependency`, only `apollo-codegen`.  Do I need `core` installed as well?

**Comment by Dremora** [comment]
@mwarger I think you need to switch to the new `apollo` package, see their [tweet](https://twitter.com/apollographql/status/1012378306195415040). I'm migrating our code right now.

**Comment by mwarger** [comment]
I hadn't seen that, thank you. I will give it a shot!
