### ISSUE TITLE
[0.20.x] tidy command line error output when --output is omitted

### ISSUE THREAD

**Issue by lirbank** [apollographql/apollo-codegen#450]
Before 0.20.x if you omitted the `--output` param the type files were colocated with the source files, but now apollo-codegen throws an error.

Colocate with source files, multiple files (omit the `--output` flag) - does not work anymore:
```
apollo-codegen generate \"src/**/*.{ts?(x),graphql}\" --schema schema.json --target typescript-modern --addTypename --tag-name gql
```

The above outputs `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined`

Single file - works:
```
apollo-codegen generate \"src/**/*.{ts?(x),graphql}\" --schema schema.json --target typescript-modern --addTypename --tag-name gql --output src/__generated__/operation-result-types.d.ts
```

Multiple files - works:
```
apollo-codegen generate \"src/**/*.{ts?(x),graphql}\" --schema schema.json --target typescript-modern --addTypename --tag-name gql --output src/__generated__/
```

Not sure if `--output` is required going forward or if this is a regression?

Possibly related to #449 and #448

**Comment by lirbank** [comment]
Update: I see now that the --output flag is required https://github.com/apollographql/apollo-codegen/blob/master/CHANGELOG.md#v0200

The printed error currently is:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.openSync (fs.js:435:3)
    at Object.writeFileSync (fs.js:1170:35)
    at Object.generate [as default] (~/node_modules/apollo-codegen/src/generate.ts:84:10)
    at Object.yargs.command.command.command.argv [as handler] (~/node_modules/apollo-codegen/src/cli.ts:213:15)
    at Object.runCommand (~/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (~/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (~/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (~/node_modules/apollo-codegen/lib/cli.js:200:5)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
error Command failed with exit code 1.

```
