### ISSUE TITLE
[Hasura] download-schema returns unknown error

### ISSUE THREAD

**Issue by sauravexodus** [apollographql/apollo-codegen#452]
I am using Hasura to create a GraphQL server. Any request from postman works just fine. But when I try to do `download-schema` or `instrospect-schema` then I get the following error.

#### Command
`apollo-codegen download-schema http://localhost:8080/v1alpha1/graphql --output schema.json`

#### Output
`error: Errors in introspection query result: [object Object]`

**Comment by sauravexodus** [comment]
I was able to generate the `schema.json` file by following this doc:

https://docs.hasura.io/0.15/platform/manual/data/graphql/schema.html

But the `generate --target "swift"` is still not working. It throws the following exception.

```
TypeError: Cannot read property 'length' of undefined
    at Object.yargs.command.command.command.argv [as handler] (/Users/sourav/.nvm/versions/node/v8.9.4/lib/node_modules/apollo-codegen/src/cli.ts:192:17)
    at Object.runCommand (/Users/sourav/.nvm/versions/node/v8.9.4/lib/node_modules/apollo-codegen/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/sourav/.nvm/versions/node/v8.9.4/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/Users/sourav/.nvm/versions/node/v8.9.4/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/sourav/.nvm/versions/node/v8.9.4/lib/node_modules/apollo-codegen/lib/cli.js:200:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by martijnwalraven** [comment]
@sauravexodus You'll need to add `.graphql` files with operations to your project and include these as input to `apollo-codegen`. (The error in the CLI should be caught and replaced by a more descriptive one.)

**Comment by sauravexodus** [comment]
Got it

**Comment by stepankuzmin** [comment]
Hi there! I'm trying to generate typings with `apollo-codegen` with my schema obtained like this:

```shell
npx graphqurl http://localhost:8080/v1alpha1/graphql --introspect > schema.graphql
```

But then I try to generate typings with:

```shell
npx apollo-codegen generate --schema schema.graphql --target ts --output types
```

I'm getting `Cannot read property 'length' of undefined`.

I'm getting the same error after trying to use introspected schema:

```shell
npx apollo-codegen introspect-schema schema.graphql --output schema.json
npx apollo-codegen generate --schema schema.json --target ts --output types
```

Am I missing something?
